### ISSUE TITLE
Error: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by prx-lmo** [DarrenPaulWright/less-themes-webpack-plugin#14]
in "new ThemesPlugin" I get following Error:
```
TypeError: Right-hand side of 'instanceof' is not an object
    at ...\node_modules\less-themes-webpack-plugin\src\Plugin.js:196:29
    at Array.some (<anonymous>)
    at ThemesPlugin._hasHtmlWebpackPlugin (...\node_modules\less-themes-webpack-plugin\src\Plugin.js:196:5)
    at ThemesPlugin.apply (...\node_modules\less-themes-webpack-plugin\src\Plugin.js:280:12)
    at createCompiler (...\node_modules\webpack\lib\webpack.js:76:12)
    at create (...\node_modules\webpack\lib\webpack.js:143:16)
    at webpack (...\node_modules\webpack\lib\webpack.js:151:47)
    at WebpackCLI.f [as webpack] (...\node_modules\webpack\lib\index.js:72:16)
    at WebpackCLI.createCompiler (...\node_modules\webpack-cli\lib\webpack-cli.js:1785:29)
    at async WebpackCLI.runWebpack (...\node_modules\webpack-cli\lib\webpack-cli.js:1877:20)
```

the error comes up here:
```
_hasHtmlWebpackPlugin(compiler) {
	return compiler.options.plugins
		.some((plugin) => plugin instanceof HtmlWebpackPlugin);
}
```

I don't use the HtmlWebpackPlugin.

thats my given config: 
```
new ThemesPlugin({
        filename: '[name].min.css',
        themesPath: './less',
        sourceMap: true,
        themes: {
            main: {
                path: 'themes',
                include: stdLessFiles,
                A: {
                    path: "./themes/A",
                    include: customLessFiles
                },
                B: {
                    path: "./themes/B",
                    include: customLessFiles
                },
                C: {
                    path: "./themes/C",
                    include: customLessFiles
                },
                D: {
                    path: "./themes/D",
                    include: customLessFiles
                },
                E: {
                    path: "./themes/E",
                    include: customLessFiles
                }
            }
        }
    })
```

I hope this project isn't dead, just sleeping.

**Comment by DarrenPaulWright** [comment]
I know it's been almost two years, but I just pushed a fix for this.
